### ISSUE TITLE
Feedback on the exchain-ethers implementation

### ISSUE THREAD

**Issue by tkaraivanov** [okblockchainlab/ethers.js#2]
Hello,

Our engineers have some feedback/questions on the implementation. See below:

**exchain-ethers**: Deploying contracts using factories using **exchain-ethers** fails the transaction hash validation. Other transactions seem to work fine. Snippet of sample error:
```
Error: Transaction hash mismatch from Provider.sendTransaction. (expectedHash="0xda6f5398d0f4b81bc4f4652d485477a0732b94996c901a80dcdf9d58ef85e299", returnedHash="0x021939ea2d094ef19f02665aabd438f4967c73ebef450683a1f5c4c717354ec3", code=UNKNOWN_ERROR, version=providers/5.5.0)
    at Logger.makeError (/home/chainlink/Documents/gauntlet/node_modules/@exchain-ethersproject/logger/src.ts/index.ts:213:28)
    at Logger.throwError (/home/chainlink/Documents/gauntlet/node_modules/@exchain-ethersproject/logger/src.ts/index.ts:225:20)
    at JsonRpcProvider.BaseProvider._wrapTransaction (/home/chainlink/Documents/gauntlet/node_modules/@exchain-ethersproject/providers/src.ts/base-provider.ts:1171:20)
    at JsonRpcProvider.<anonymous> (/home/chainlink/Documents/gauntlet/node_modules/@exchain-ethersproject/providers/src.ts/base-provider.ts:1217:25)
    at step (/home/chainlink/Documents/gauntlet/node_modules/@exchain-ethersproject/providers/lib/base-provider.js:48:23)
    at Object.next (/home/chainlink/Documents/gauntlet/node_modules/@exchain-ethersproject/providers/lib/base-provider.js:29:53)
    at fulfilled (/home/chainlink/Documents/gauntlet/node_modules/@exchain-ethersproject/providers/lib/base-provider.js:20:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  reason: 'Transaction hash mismatch from Provider.sendTransaction.',
  code: 'UNKNOWN_ERROR',
  expectedHash: '0xda6f5398d0f4b81bc4f4652d485477a0732b94996c901a80dcdf9d58ef85e299',
  returnedHash: '0x021939ea2d094ef19f02665aabd438f4967c73ebef450683a1f5c4c717354ec3',
```
**exchain-ethers**: the package is always logging transaction hash inputs (nonce, price, gasLimit, recipient, v, r, s, etc). Could this be removed since it clutters the CLI outputs quite a bit for larger transactions?

**websocket rpc**: Does the websocket support making batch requests (if they do, how is the performance for the request)? [See here for geth interface](https://github.com/ethereum/go-ethereum/blob/d8ff53dfb8a516f47db37dbc7fd7ad18a1e8a125/rpc/client.go#L323). Specific example is using batch requests to retrieve blocks with **eth_getBlockByNumber**.

**Comment by summerpro** [comment]
the package is always logging transaction hash inputs (nonce, price, gasLimit, recipient, v, r, s, etc). Could this be removed since it clutters the CLI outputs quite a bit for larger transactions?

We will delete it in the next release

**Comment by summerpro** [comment]
> Hello,
> 
> Our engineers have some feedback/questions on the implementation. See below:
> 
> **exchain-ethers**: Deploying contracts using factories using **exchain-ethers** fails the transaction hash validation. Other transactions seem to work fine. Snippet of sample error:
> 
> ```
> Error: Transaction hash mismatch from Provider.sendTransaction. (expectedHash="0xda6f5398d0f4b81bc4f4652d485477a0732b94996c901a80dcdf9d58ef85e299", returnedHash="0x021939ea2d094ef19f02665aabd438f4967c73ebef450683a1f5c4c717354ec3", code=UNKNOWN_ERROR, version=providers/5.5.0)
>     at Logger.makeError (/home/chainlink/Documents/gauntlet/node_modules/@exchain-ethersproject/logger/src.ts/index.ts:213:28)
>     at Logger.throwError (/home/chainlink/Documents/gauntlet/node_modules/@exchain-ethersproject/logger/src.ts/index.ts:225:20)
>     at JsonRpcProvider.BaseProvider._wrapTransaction (/home/chainlink/Documents/gauntlet/node_modules/@exchain-ethersproject/providers/src.ts/base-provider.ts:1171:20)
>     at JsonRpcProvider.<anonymous> (/home/chainlink/Documents/gauntlet/node_modules/@exchain-ethersproject/providers/src.ts/base-provider.ts:1217:25)
>     at step (/home/chainlink/Documents/gauntlet/node_modules/@exchain-ethersproject/providers/lib/base-provider.js:48:23)
>     at Object.next (/home/chainlink/Documents/gauntlet/node_modules/@exchain-ethersproject/providers/lib/base-provider.js:29:53)
>     at fulfilled (/home/chainlink/Documents/gauntlet/node_modules/@exchain-ethersproject/providers/lib/base-provider.js:20:58)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
>   reason: 'Transaction hash mismatch from Provider.sendTransaction.',
>   code: 'UNKNOWN_ERROR',
>   expectedHash: '0xda6f5398d0f4b81bc4f4652d485477a0732b94996c901a80dcdf9d58ef85e299',
>   returnedHash: '0x021939ea2d094ef19f02665aabd438f4967c73ebef450683a1f5c4c717354ec3',
> ```
> 
> **exchain-ethers**: the package is always logging transaction hash inputs (nonce, price, gasLimit, recipient, v, r, s, etc). Could this be removed since it clutters the CLI outputs quite a bit for larger transactions?
> 
> **websocket rpc**: Does the websocket support making batch requests (if they do, how is the performance for the request)? [See here for geth interface](https://github.com/ethereum/go-ethereum/blob/d8ff53dfb8a516f47db37dbc7fd7ad18a1e8a125/rpc/client.go#L323). Specific example is using batch requests to retrieve blocks with **eth_getBlockByNumber**.

Can you help me take a look, what is the difference between the problematic tx struct and the normal tx struct?
